embeddings {
  tensor_name: "fmnist_embedding:0"
  metadata_path: "/home/kvishesh/Desktop/fashion mnist/log1/metadata.tsv"
  sprite {
    image_path: "/home/kvishesh/Desktop/fashion mnist/log1/sprite.png"
    single_image_dim: 28
    single_image_dim: 28
  }
}
